---
name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    outputs:
      sha8: ${{ steps.release_version.outputs.sha8 }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Get release version
      id: release_version
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        pull: true
        push: true
        tags: |
          ghcr.io/speer/prometheus-sample-app:latest
          ghcr.io/speer/prometheus-sample-app:${{ steps.release_version.outputs.sha8 }}
